feat: auto-generate css vars from theme vars
greymatter-io/gm-ui-components pull request #608
Opened 2020-11-29 15:27 UTC by shanberg

Map over the actual theme variables to generate the CSS vars, rather than hardcoding them.

2021-05-25 13:38 UTC, kaitmore approved these changes
Looks good 
![image](https://user-images.githubusercontent.com/22768918/119507605-fae60c80-bd3c-11eb-9b94-f96c115a0490.png)

2021-05-25 13:39 UTC, kaitmore requested changes
Sorry missed this

2021-05-25 17:27 UTC, shanberg commented on src/style/GlobalStyles.js
> -    --ZINDEX_MODAL: ${({ theme }) => theme.ZINDEX_MODAL}
@kaitmore This looks to have been a caching issue. Try a hard refresh and see if it goes away. It did for me.

2021-09-02 20:51 UTC, tilleryd approved these changes
Smoke tested in the dashboard and all looks good.

2021-09-02 20:55 UTC, merged