chore: [sc-18945] Review all copyright messages in source code and make sure they are greymatter.io, not Decipher.
greymatter-io/gm-ui-components pull request #639
Opened 2022-07-13 12:57 UTC by abhay-greymatter

Story details: https://app.shortcut.com/grey-matter/story/18945

2022-07-13 13:21 UTC, ChocoTaco12 submitted a review, later dismissed

2022-07-13 16:52 UTC, tilleryd commented on LICENSE
> +Copyright (c) 2022 greymatter.io
```suggestion
Copyright (c) 2022 greymatter.io Inc
```

2022-07-13 16:52 UTC, tilleryd requested changes
Just one comment on Inc

2022-07-13 18:27 UTC, tilleryd approved these changes

2022-07-15 19:36 UTC, tilleryd approved these changes

2022-07-15 20:00 UTC, merged